#pragma once

#include <Aurora/Mathematics/angle.h>
#include <Aurora/Mathematics/bounds.h>
#include <Aurora/Mathematics/col.h>
#include <Aurora/Mathematics/col32.h>
#include <Aurora/Mathematics/hsv.h>
#include <Aurora/Mathematics/ibounds.h>
#include <Aurora/Mathematics/irect.h>
#include <Aurora/Mathematics/ivec2.h>
#include <Aurora/Mathematics/ivec3.h>
#include <Aurora/Mathematics/ivec4.h>
#include <Aurora/Mathematics/LerpDirection.h>
#include <Aurora/Mathematics/mat2.h>
#include <Aurora/Mathematics/mat3.h>
#include <Aurora/Mathematics/mat4.h>
#include <Aurora/Mathematics/math.h>
#include <Aurora/Mathematics/matrix.h>
#include <Aurora/Mathematics/Quality.h>
#include <Aurora/Mathematics/quat.h>
#include <Aurora/Mathematics/rect.h>
#include <Aurora/Mathematics/temperature.h>
#include <Aurora/Mathematics/vec2.h>
#include <Aurora/Mathematics/vec3.h>
#include <Aurora/Mathematics/vec4.h>
